"""add course to LearningDay

Revision ID: 0179e761bb5c
Revises: bb0e157c6c24
Create Date: 2024-10-02 02:32:16.260658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0179e761bb5c'
down_revision: Union[str, None] = 'bb0e157c6c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_days', sa.Column('course', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_days', 'course')
    # ### end Alembic commands ###
