"""add new fields to LearningDay

Revision ID: 1c665cbbbd5f
Revises: 79cb7aceaaae
Create Date: 2024-10-01 19:32:33.658735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c665cbbbd5f'
down_revision: Union[str, None] = '79cb7aceaaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_days', sa.Column('learning_methods', sa.String(), nullable=True))
    op.add_column('learning_days', sa.Column('online_groups_and_forums', sa.String(), nullable=True))
    op.add_column('learning_days', sa.Column('time_planning', sa.String(), nullable=True))
    op.add_column('learning_days', sa.Column('course_level', sa.String(), nullable=True))
    op.add_column('learning_days', sa.Column('course_teacher', sa.String(), nullable=True))
    op.add_column('learning_days', sa.Column('course_type', sa.String(), nullable=True))
    op.add_column('learning_days', sa.Column('fee', sa.String(), nullable=True))
    op.add_column('learning_days', sa.Column('has_certificate', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_days', 'has_certificate')
    op.drop_column('learning_days', 'fee')
    op.drop_column('learning_days', 'course_type')
    op.drop_column('learning_days', 'course_teacher')
    op.drop_column('learning_days', 'course_level')
    op.drop_column('learning_days', 'time_planning')
    op.drop_column('learning_days', 'online_groups_and_forums')
    op.drop_column('learning_days', 'learning_methods')
    # ### end Alembic commands ###
