"""add specific_tool to input model

Revision ID: 79cb7aceaaae
Revises: a6c73b594f1f
Create Date: 2024-10-01 18:08:28.340350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79cb7aceaaae'
down_revision: Union[str, None] = 'a6c73b594f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs', sa.Column('specific_tool', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inputs', 'specific_tool')
    # ### end Alembic commands ###
