"""fix field name

Revision ID: afcd425701e7
Revises: 84810d744a03
Create Date: 2024-09-30 00:17:46.042618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afcd425701e7'
down_revision: Union[str, None] = '84810d744a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs', sa.Column('learning_style', sa.ARRAY(sa.String()), nullable=False))
    op.drop_column('inputs', 'learnig_style')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs', sa.Column('learnig_style', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('inputs', 'learning_style')
    # ### end Alembic commands ###
