"""add deadline and remove specific_fild from Input

Revision ID: be17b4d24c42
Revises: e5f7771cc003
Create Date: 2024-09-29 17:14:22.289155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be17b4d24c42'
down_revision: Union[str, None] = 'e5f7771cc003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'inputs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inputs', type_='foreignkey')
    op.drop_column('inputs', 'user_id')
    # ### end Alembic commands ###
